version: "3.8"
services:
  app_react:
    build: ./user-list-front
    container_name: app_react
    environment:
      VITE_API_BASE_URL: http://localhost/api-node
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_node

  database:
    image: postgres
    container_name: database
    ports:
      - 2345:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: userlist
    volumes:
      - volume_database:/var/lib/postgresql/data

  app_node:
    build: ./user-list-back
    container_name: app_node
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      JWT_SECRET: 46b4a578858dd28e312548cec598090c4ba0d4af
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: userlist
    volumes:
      - ./user-list-back:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://database:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run start"
    depends_on:
      - database

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react

volumes:
  build_react:
  volume_database: